module.exports = [
    {type: "arr", name: "Array value"},
    {type: "map", name: "Google map"},
    {type: "checkbox", name: "Checkbox"},
    {type: "radio", name: "Radio"},
    {type: "date", name: "Date"},
    {type: "email", name: "Email"},
    {type: "file", name: "File(s)"},
    {type: "number", name: "Number"},
    {type: "decimal", name: "Decimal"},
    {type: "password", name: "Password"},
    {type: "select", name: "Selectbox"},
    {type: "select_lookup", name: "Select from another table"},
    {type: "tel", name: "Telephone Number"},
    {type: "text", name: "Text"},
    {type: "textarea", name: "Textarea"},
    {type: "texteditor", name: "Textarea and Editor"},
    {type: "url", name: "URL"},
    {type: "label", name: "Label"},
    {type: "header", name: "Group"},
    {type: "time", name: "Time"},
]